version: '3.8'

services:
  # API
  backend:
    container_name: express
    image: express:local
    build:
      context: ./express
      dockerfile: Dockerfile
    volumes:
      - ./src:/express
    ports: 
      - 8080:8080
  # CLIENT
  frontend:
    container_name: react-app
    image: react-app:local
    build:
      context: ./react-app
      # target: development
      dockerfile: Dockerfile
    volumes:
       - ./src:/react-app/src
    ports:
      - 3000:3000